# Generated by Django 5.0.7 on 2024-07-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discout_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
