# Generated by Django 5.0.7 on 2024-07-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discout_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description dqwttq qqwqdgevcd wacxcdv'),
            preserve_default=False,
        ),
    ]
